# Generated by Django 5.2.4 on 2025-07-11 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('BARAUNA', 'Baraúna')], max_length=100, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(choices=[('RN', 'Rio Grande do Norte')], max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='denuncias/')),
                ('nome_denunciante', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('situacao', models.CharField(choices=[('NAO_RESOLVIDO', 'NÃO RESOLVIDO'), ('RESOLVIDO', 'RESOLVIDO')], default='NAO_RESOLVIDO', max_length=20)),
                ('ativo', models.BooleanField(default=False)),
                ('contagem_denuncias', models.PositiveIntegerField(default=1)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidadedenuncia')),
            ],
        ),
    ]
