# Generated by Django 5.2.4 on 2025-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_denunciadetalhada'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='resolvido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cidadedenuncia',
            name='nome',
            field=models.CharField(choices=[('BARAUNA', 'Baraúna'), ('MOSSORO', 'Mossóro')], max_length=100, unique=True),
        ),
    ]
