# Generated by Django 5.2.4 on 2025-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_denuncia_resolvido_alter_cidadedenuncia_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadedenuncia',
            name='nome',
            field=models.CharField(choices=[('BARAUNA', 'Baraúna'), ('MOSSORO', 'Mossóro'), ('NATAL', 'Natal')], max_length=100, unique=True),
        ),
    ]
