# Generated by Django 5.2.4 on 2025-08-06 20:45

import cloudinary_storage.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cidadedenuncia_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField(max_length=300)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='foto',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='denuncias/'),
            preserve_default=False,
        ),
    ]
