# Generated by Django 5.2.4 on 2025-08-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mensagem_alter_denuncia_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Mensagem_Contato',
        ),
    ]
